name: blockbench-snapcraft
title: Blockbench
summary: Blockbench - A boxy 3D model editor
description: |
  Blockbench is a free, modern model editor for low-poly and boxy models with pixel art textures.
  Models can be exported into standardized formats, to be shared, rendered, 3D-printed, or used in game engines. There are also multiple dedicated formats for Minecraft Java and Bedrock Edition with format-specific features. 

  Blockbench features a modern and intuitive UI, plugin support and innovative features. It is the industry standard for creating custom 3D models for the Minecraft Marketplace.
website: https://www.blockbench.net/
contact: https://github.com/anrouxel/blockbench-snapcraft/issues
issues: https://github.com/anrouxel/blockbench-snapcraft/issues
source-code: https://github.com/anrouxel/blockbench-snapcraft
license: GPL-3.0
adopt-info: blockbench-snapcraft
icon: snap/gui/blockbench-snapcraft.png
version: 5.0.2

base: core24
grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:
  arm64:

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/imlib2:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/imlib2
  /usr/share/X11/XErrorDB:
    symlink: $SNAP/gpu-2404/X11/XErrorDB

plugs:
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404

apps:
  blockbench-snapcraft:
    extensions: [gnome]
    command-chain:
      - bin/gpu-2404-wrapper
    command: usr/bin/blockbench-snapcraft-wrapper
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
      # Included temporarily until https://github.com/snapcore/snapcraft-desktop-integration/issues/28
      # is resolved.
      NOTIFY_IGNORE_PORTAL: 1
    plugs:
      - desktop
      - desktop-legacy
      - opengl
      - x11
      - wayland
      - gsettings
      - pulseaudio
      - browser-support
      - home
      - network
      - audio-playback
      - audio-record
      - removable-media
      - unity7
      - screen-inhibit-control

parts:
  blockbench-snapcraft:
    plugin: dump
    source: https://github.com/JannisX11/blockbench.git
    source-type: git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    override-build: |
      npm install
      npm run build-electron
      npx electron-builder --linux -c.linux.target=dir
      mkdir -p "${CRAFT_PART_INSTALL}/opt"
      mv dist-electron/linux-*unpacked "${CRAFT_PART_INSTALL}/opt/Blockbench"
    build-snaps:
      - node/24/stable
    prime:
      - -opt/Blockbench/chrome-sandbox
      - -opt/Blockbench/resources/app.asar.unpacked/node_modules/sharp/vendor/lib
      - -opt/Blockbench/resources/app.asar.unpacked/node_modules/sharp/vendor/include

  gpu-2404:
    after: [blockbench-snapcraft]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
    - bin/gpu-2404-wrapper

  libs:
    after: [blockbench-snapcraft]
    plugin: nil
    stage-packages:
      - libimlib2t64

  local-parts:
    plugin: dump
    source: ./snap/local
    source-type: local