name: blockbench-snapcraft
version: v4.10.4
summary: Blockbench - A boxy 3D model editor
description: |
  Blockbench - A boxy 3D model editor
icon: snap/gui/blockbench_logo.png
license: GPL-3.0

base: core24
grade: stable
confinement: strict
adopt-info: blockbench-snapcraft
compression: lzo

platforms:
  amd64:
  arm64:
  armhf:

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/imlib2:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/imlib2

apps:
  blockbench:
    extensions: [gnome]
    command: Blockbench --no-sandbox
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - desktop
      - desktop-legacy
      - home
      - opengl
      - x11
      - unity7
      - wayland
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - audio-playback

parts:
  libs:
    plugin: nil
    stage-packages:
      - libimlib2t64

  blockbench:
    plugin: nil
    source: https://github.com/JannisX11/blockbench.git
    source-type: git
    override-pull: |
      craftctl default
      git checkout "$SNAPCRAFT_PROJECT_VERSION" -b latest
    build-environment:
      - PATH: "$PATH:$CRAFT_PART_BUILD/node_modules/.bin"
    override-build: |
      set +u # core20 base does not allow unbound variables !
      # workaround for build.snapcraft.io builds
      # https://bugs.launchpad.net/bugs/1886861
      if [ -n "$http_proxy" ]; then
        export ELECTRON_GET_USE_PROXY=1
        export GLOBAL_AGENT_HTTP_PROXY="${http_proxy}"
        export GLOBAL_AGENT_HTTPS_PROXY="${http_proxy}"
      fi
      npm install
      npm i electron-packager
      npx electron-packager . --overwrite --platform=linux --output=release-build \
        --prune=true
      mv Blockbench-linux-*/* $CRAFT_PART_INSTALL
      # Strip the executable stack bit on libde265.so
      # Only armhf requires this modification, arm64 and amd64 both pass the
      # automated store validation (i.e review-tools.snap-review)
      if [ $CRAFT_ARCH_BUILD_FOR = "arm-linux-gnueabihf" ]; then
        execstack --clear-execstack $SNAPCRAFT_PART_INSTALL/usr/lib/*/libde265.so.*
      fi
    build-packages:
      - git
      - sed
      - execstack
    build-snaps:
      - node/20/stable
