name: blockbench-snapcraft
title: Blockbench
summary: Blockbench - A boxy 3D model editor
description: |
  Blockbench is a free, modern model editor for low-poly and boxy models with pixel art textures.
  Models can be exported into standardized formats, to be shared, rendered, 3D-printed, or used in game engines. There are also multiple dedicated formats for Minecraft Java and Bedrock Edition with format-specific features. 

  Blockbench features a modern and intuitive UI, plugin support and innovative features. It is the industry standard for creating custom 3D models for the Minecraft Marketplace.
website: https://www.blockbench.net/
contact: https://github.com/anrouxel/blockbench-snapcraft/issues
issues: https://github.com/anrouxel/blockbench-snapcraft/issues
source-code: https://github.com/anrouxel/blockbench-snapcraft
license: GPL-3.0
adopt-info: blockbench-snapcraft
icon: snap/gui/blockbench_logo.png
version: 5.0.3

base: core24
grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:
  arm64:

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/imlib2:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/imlib2
  /usr/share/X11/XErrorDB:
    symlink: $SNAP/gpu-2404/X11/XErrorDB

plugs:
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404

apps:
  blockbench-snapcraft:
    extensions: [gnome]
    command-chain:
      - bin/gpu-2404-wrapper
    command: blockbench --no-sandbox
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
      # Included temporarily until https://github.com/snapcore/snapcraft-desktop-integration/issues/28
      # is resolved.
      NOTIFY_IGNORE_PORTAL: 1
    plugs:
      - desktop
      - desktop-legacy
      - opengl
      - x11
      - wayland
      - gsettings
      - pulseaudio
      - browser-support
      - home
      - network
      - audio-playback
      - audio-record
      - removable-media
      - unity7
      - screen-inhibit-control

parts:
  blockbench-snapcraft:
    plugin: dump
    source: https://github.com/JannisX11/blockbench.git
    source-type: git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    override-build: |
      # Setup proxy access where needed
      if [[ -n "${http_proxy:-}" ]]; then
        export HTTP_PROXY="${http_proxy:-}"
        export HTTPS_PROXY="${http_proxy:-}"
        export ELECTRON_GET_USE_PROXY=1
        export GLOBAL_AGENT_HTTP_PROXY="${http_proxy:-}"
        export GLOBAL_AGENT_HTTPS_PROXY="${http_proxy:-}"
      fi
      npm install
      npm run build-electron
      npx electron-builder --linux -c.linux.target=dir
      mv dist-electron/linux*-unpacked/* $CRAFT_PART_INSTALL
    build-snaps:
      - node/24/stable

  gpu-2404:
    after: [blockbench-snapcraft]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
    - bin/gpu-2404-wrapper

  libs:
    after: [blockbench-snapcraft]
    plugin: nil
    stage-packages:
      - libimlib2t64

